### DISCUSSION TITLE
V3 Migration - devices.yaml not picked up

### DISCUSSION THREAD

**Discussion by vijay-hcl-epl** [edgexfoundry/community#177] [Q&A] [answered]
Hi all,
I am migrating a device service to EdgeX 3.0 with CSDK 3.0.2. Below is my devices.yaml file which is not picked up after the device service started. I already validated in yaml validator

devices.yaml(sorry not able to put it inside code format)

>   - name: "candev"
    profileName: "canprofile"
    description: "Example can device"
    labels:
      - can
      - bus
    protocols:
      other: {}
    autoEvents:
      - Interval: 10s
        OnChange: false
        SourceName: can_rdmsg

However below is the devices file in json format which is picked up by the device service

> [
  {
    "name": "candev",
    "profileName": "canprofile",
    "description": "Example can device",
    "labels": [ "can", "bus" ],
    "protocols": {
      "Counter": { "Index": "3" }
   },
   "autoEvents":
    [
      { "sourceName": "can_rdmsg", "onChange": false, "interval": "10s" }
    ]
  }
]

Could you please let us know how to ensure that the device service picks up devices.yaml file in V3?

Thank You,
Vijay

**Comment by lenny-goodell** [comment]
Indentation in YAML is very important. Also the casing for most items (except Protocol elements) must be camelCase

Try this:
```
- name: "candev"
  profileName: "canprofile"
  description: "Example can device"
  labels:
    - can
    - bus
  protocols:
    other: {}
  autoEvents:
    - interval: 10s
      onChange: false
      sourceName: can_rdmsg
```
