### DISCUSSION TITLE
Failed to create Redis Streams client: Connection refused

### DISCUSSION THREAD

**Discussion by bighb69738** [edgexfoundry/community#210] [Q&A] [answered]
It is my error message 
level=INFO ts=2023-11-23T03:30:43Z app=device-template msg="Message Bus is set to Redis streams at localhost:6379"
level=ERROR ts=2023-11-23T03:30:43Z app=device-template msg="Failed to create Redis Streams client: Connection refused"
level=ERROR ts=2023-11-23T03:30:43Z app=device-template msg="Failed to create Redis Streams client: Connection refused"
level=ERROR ts=2023-11-23T03:30:44Z app=device-template msg="Failed to create Redis Streams client: Connection refused"
level=ERROR ts=2023-11-23T03:30:44Z app=device-template msg="Failed to create Redis Streams client: Connection refused"
level=INFO ts=2023-11-23T03:30:45Z app=device-template msg="Reconfiguring"
level=ERROR ts=2023-11-23T03:30:45Z app=device-template msg="Failed to create Redis Streams client: Connection refused"
level=ERROR ts=2023-11-23T03:30:45Z app=device-template msg="Failed to create Redis Streams client: Connection refused"

Configuration 
```
Writable:
  LogLevel: DEBUG
  Device:
    Discovery:
      Enabled: true

Service:
  Host: localhost
  Port: 59990
  StartupMsg: Template device started

Clients:
  core-metadata:
    Host: localhost
    Port: 59881

Device:
  ProfilesDir: "./res/profiles"
  #DevicesDir: "./res/devices"

MessageBus:
  Protocol: redis
  Host: localhost
  Port: 6379
  Type: redis
  AuthMode: "usernamepassword"  # required for redis messagebus (secure or insecure)
  SecretName: redisdb
  Optional:
    ClientId: device-example
```
