### DISCUSSION TITLE
How to modify RequestTimeout in configuration.yaml

### DISCUSSION THREAD

**Discussion by bighb69738** [edgexfoundry/community#216] [Q&A] [answered]
```
MaxEventSize: 0
Writable:
  LogLevel: DEBUG
  Device:
    Discovery:
      Enabled: true

Service:
  Host: "localhost"
  Port: 59990
  StartupMsg: Template device started
  RequestTimeout: "20s" // Fail

Device:
  ProfilesDir: "./res/profiles"

MessageBus:
  Protocol: redis
  Host: edgex-redis
  Port: 6379
  Type: redis
  AuthMode: "usernamepassword"  # required for redis messagebus (secure or insecure)
  SecretName: redisdb
  Optional:
    ClientId: device-example
```

info message:
level=DEBUG ts=2023-11-27T06:45:56Z app=edgex-device-example msg="Service/RequestTimeout="5s""

**Comment by jiekechoo** [comment]
@bighb69738 
There two options:
- add to docker-compose.yml
```
Service:
    environment:
       SERVICE_REQUESTTIMEOUT: "20s"
```
- the same as your `configuration.yaml`

here is a doc you can refer: https://docs.edgexfoundry.org/3.1/microservices/configuration/CommonEnvironmentVariables/ 

Jieke
YIQISOFT

**Reply by bighb69738** [reply]
@jiekechoo  
How to fix command timeout?

```
Service:
    environment:
       SERVICE_REQUESTTIMEOUT: "20s"
```

Add this environment in edgex-core-command service ?

**Reply by jiekechoo** [reply]
Any micro service if you want. It's a common env varible.

**Reply by bighb69738** [reply]
Hi @jiekechoo 

I added the  SERVICE_REQUESTTIMEOUT: "20s" in the edgex-core-command service, but it is not work.

level=WARN ts=2023-11-27T08:22:07.609578551Z app=core-command source=config.go:1064 msg="waiting for Common Configuration to be available from config provider"
level=WARN ts=2023-11-27T08:22:08.614024862Z app=core-command source=config.go:1064 msg="waiting for Common Configuration to be available from config provider"
level=INFO ts=2023-11-27T08:22:09.634374779Z app=core-command source=config.go:173 msg="Common configuration loaded from the Configuration Provider. No overrides applied"
level=INFO ts=2023-11-27T08:22:09.634595098Z app=core-command source=config.go:718 msg="Using Configuration provider (consul) from: http://edgex-core-consul:8500 with base path of edgex/v3/core-command"
level=INFO ts=2023-11-27T08:22:09.647931202Z app=core-command source=config.go:731 msg="Loading configuration file from res/configuration.yaml"
level=INFO ts=2023-11-27T08:22:09.649849868Z app=core-command source=variables.go:462 msg="Variables override of 'Service/Host' by environment variable: SERVICE_HOST=edgex-core-command"
level=INFO ts=2023-11-27T08:22:09.650010787Z app=core-command source=variables.go:462 msg="Variables override of 'Writable/LogLevel' by environment variable: WRITABLE_LOGLEVEL=DEBUG"
level=INFO ts=2023-11-27T08:22:09.650057947Z app=core-command source=variables.go:462 msg="Variables override of 'ExternalMQTT/Url' by environment variable: EXTERNALMQTT_URL=tcp://edgex-mqtt-broker:1883"
level=INFO ts=2023-11-27T08:22:09.650102467Z app=core-command source=config.go:251 msg="Private configuration loaded from file with 3 overrides applied"
level=INFO ts=2023-11-27T08:22:12.098415016Z app=core-command source=config.go:262 msg="Private configuration has been pushed to into Configuration Provider with overrides applied"
level=INFO ts=2023-11-27T08:22:12.098864172Z app=core-command source=config.go:269 msg="listening for private config changes"
level=INFO ts=2023-11-27T08:22:12.099577567Z app=core-command source=config.go:271 msg="listening for all services common config changes"
level=INFO ts=2023-11-27T08:22:12.103022502Z app=core-command source=registry.go:61 msg="Using Registry access token of length 0"
level=INFO ts=2023-11-27T08:22:12.103094742Z app=core-command source=registry.go:89 msg="Using Registry (consul) from http://edgex-core-consul:8500"

docker-compose
```
core-command:
    container_name: edgex-core-command
    depends_on:
      consul:
        condition: service_started
      core-metadata:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      EXTERNALMQTT_URL: tcp://edgex-mqtt-broker:1883
      SERVICE_HOST: edgex-core-command
      SERVICE_REQUESTTIMEOUT: "20s"
      WRITABLE_LOGLEVEL: DEBUG
    hostname: edgex-core-command
    image: edgexfoundry/core-command-arm64:3.1.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 0.0.0.0
      target: 59882
      published: 59882
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
```

**Reply by jiekechoo** [reply]
What's your EdgeX version?

**Reply by jiekechoo** [reply]
access the url `http://localhost:59882/api/v3/config`, checkout the `Service` section in json:

```
  "Service": {
...
      "Host": "edgex-core-command",
      "Port": 59882,
      "RequestTimeout": "50s",
....
```

**Reply by bighb69738** [reply]
@jiekechoo  EdgeX v3.1.0

http://localhost:59882/api/v3/config
```
  "EnableNameFieldEscape": false,
  "HealthCheckInterval": "10s",
  "Host": "edgex-core-command",
  "MaxRequestSize": 0,
  "MaxResultCount": 1024,
  "Port": 59882,
  "RequestTimeout": "5s",
  "ServerBindAddr": "",
  "StartupMsg": "This is the Core Command Microservice"
```

**Reply by jiekechoo** [reply]
Comfirmed, It's a big bug, I think.

**Reply by bighb69738** [reply]
@jiekechoo 

Will it release a new version to fix this error ?

**Reply by jiekechoo** [reply]
I can't fix this error. So, I'll create a new issue.

**Reply by lenny-goodell** [reply]
@jiekechoo , this is working as indented. See note at the bottom of this Docs section and my comments on the issue you created.
https://docs.edgexfoundry.org/3.1/microservices/configuration/CommonEnvironmentVariables/#service-configuration-overrides

**Reply by jiekechoo** [reply]
@bighb69738 

As @lenny-intel metioned. Thanks for your help. 👍 

 I got the solutions. 

**Delete all volmues before starting docker containers.** 

```shell
cd compose-builder
make clean
```

## Option 1: 
add a global env in `core-common-config-bootstrapper` service
```
  core-common-config-bootstrapper:
 ...
    environment:
...
      ALL_SERVICES_SERVICE_REQUESTTIMEOUT: 60s
...
```
it works.

in `core-metadata`
![image](https://github.com/edgexfoundry/community/assets/3350211/b1420995-768f-41d0-ac8f-9614492d81a9)

in `core-command`
![image](https://github.com/edgexfoundry/community/assets/3350211/f970721a-2c2d-4472-9213-7461a3b817e6)


## Option 2:

mount local directory `./res` to container's volume `/res` in docker-compose.yml

```
    volumes:
...
      - type: bind
        source: ./res
        target: /res
        bind:
          create_host_path: true
...
```

and add `RequestTimeout` to local `./res/configuration.yaml`
```
Service:
...
  RequestTimeout: 50s
...
```

finally, start docker.

```
docker compose -p edgex up -d
```

it works.

![image](https://github.com/edgexfoundry/community/assets/3350211/c8dfdbdd-0345-4ac7-90a9-5b1764d227f5)


Jieke
YIQISOFT
