### DISCUSSION TITLE
How to overwrite the intervaltime in support-scheduler?

### DISCUSSION THREAD

**Discussion by bighb69738** [edgexfoundry/community#219] [Q&A] [answered]
I tried to overwrite interval time

configuration.yaml
```
ScheduleIntervalTime: 500
Writable:
    LogLevel: INFO
Service:
    Host: localhost
    Port: 59861
    StartupMsg: "This is the Support Scheduler Microservice"
Intervals:
    Midnight:
        Name: midnight
        Start: 20180101T000000
        Interval: 2h
    Fiveminutes:
        Name: 5m
        Start: 20180101T000000
        Interval: 5m
IntervalActions:
    ScrubAged:
        Name: scrub-aged-events
        Host: localhost
        Port: 59880
        Protocol: http
        Method: DELETE
        Path: /api/v3/event/age/604800000000000   # Remove events older than 7 days
        Interval: midnight
        AdminState: UNLOCKED
        AuthMethod: JWT     # AuthMethod = JWT degrades to no auth in security-disabled EdgeX

MessageBus:
  Optional:
    ClientId: support-scheduler

Database:
  Name: scheduler
```

docker-compose
```
support-scheduler:
   ...
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      bind:
        create_host_path: true
    - type: volume
      source: ./res/support-scheduler
      target: /res

```
But it does not change on dashboard 

<img width="1109" alt="截圖 2023-11-29 下午5 33 12" src="https://github.com/edgexfoundry/community/assets/38970513/f57f7378-4c66-460b-9111-84f241b8ae37">
