### DISCUSSION TITLE
app-service-configurable metrics-influxdb does not recieve metrics as corresponding redis key does not exist

### DISCUSSION THREAD

**Discussion by b4zs** [edgexfoundry/community#245] [Q&A] [answered]
I am trying to use app-service-configurable with the metrics-influxdb profile to push data to InfluxDB. 
I have the basic docker setup with device-virtual enabled, and I see its data stream on the GUI (DataCenter/Reading). 
As far as I understand this profile subscribes to `edgex/telemetry/#`  and forwards data via HTTP, but this topic does not exist in the database.
Listing the redis keys returns a long list, each starting with patterns like "cd|rd", "md|dp", "ss|iv", etc, but not one named "edgex". Isn't the messagebus readable via redis-cli or what am I missing?
Thanks.

**Comment by jiekechoo** [comment]
@b4zs What is the EdgeX version? and any details about your environment？such as: app configuration, InfluxDB configuration, ...

**Reply by b4zs** [reply]
I am using version 3.1, Napa, with the generated docker compose file, that uses the edgexfoundry/service-name:3.1.0 images. 
In case of InfluxDB, I am using the latest version.

```
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - default
      - edgex-network
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./var/influxdb2/db:/var/lib/influxdb2
```

I do not think that this is related to InfluxDB, as it is the exporter service that can not subscribe to the corresponding topic:

```
  app-influxdb-export:
    image: edgexfoundry/app-service-configurable:3.1.0
    container_name: app-influxdb-export
    hostname: app-influxdb-export
    depends_on:
      - consul
      - core-data
    environment:
      EDGEX_PROFILE: metrics-influxdb # @see https://github.com/edgexfoundry/app-service-configurable/blob/v3.1.0/res/metrics-influxdb/configuration.yaml
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: app-influxdb-export
      DATABASE_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      WRITABLE_PIPELINE_FUNCTIONS_HTTPEXPORT_PARAMETERS_URL: "http://app-debug-http:8080/api/v2/write?org=sample-org&bucket=${INFLUX_BUCKET}&precision=ns"
      WRITABLE_INSECURESECRETS_INFLUXDB_SECRETDATA_TOKEN: "Token ${INFLUX_TOKEN}"
    networks:
      - default
      - edgex-network
    ports:
      - 127.0.0.1:59708:59707/tcp
    read_only: true
    security_opt:
      - no-new-privileges:true
```
(no extra configuration file mounted)

I have also tried to send the data to a custom HTTP service (mendhak/http-https-echo), this is why the `HTTPEXPORT_PARAMETERS_URL` points to app-debug-http.
Is there any way to monitor the internal message bus to check whether the `telemetry/#` topic has content?

Thank you.

**Reply by jiekechoo** [reply]
> I am trying to use app-service-configurable with the metrics-influxdb profile to push data to InfluxDB.

Sorry, I don't get your point.

But,
- Here is the `metrics-influxdb`  [doc](https://docs.edgexfoundry.org/3.1/microservices/application/services/AppServiceConfigurable/details/Profiles/#metrics-influxdb)

- Here is the [Influxdb Export](https://github.com/edgexfoundry/edgex-examples/tree/v3.1/application-services/custom/influxdb-export)

Which one do you want?

**Comment by lenny-goodell** [comment]
> Listing the redis keys returns a long list, each starting with patterns like "cd|rd", "md|dp", "ss|iv", etc, but not one named "edgex". Isn't the messagebus readable via redis-cli or what am I missing?

@b4zs , Edgex uses [Redis Pub/Sub](https://redis.io/docs/interact/pubsub/) not Streams. The topics will not show up in keys.

> Is there any way to monitor the internal message bus to check whether the `telemetry/#` topic has content?

See link above. You should be able to subscribe via the CLI using PSUBSCRIBE to `edgex.telemetry.*`

Note the change in syntaxe for level separator and wildcard when using the Redis CLI

**Comment by lenny-goodell** [comment]
> I am using version 3.1, Napa, with the generated docker compose file, that uses the edgexfoundry/service-name:3.1.0 images.

You `app-metrics-influxdb` YAML above is a mix of  3.1 and 2,x yaml. Here is what it should look like for Napa:
```
  app-metrics-influxdb:
    container_name: edgex-app-metrics-influxdb
    depends_on:
      consul:
        condition: service_started
      core-data:
        condition: service_started
    environment:
      EDGEX_PROFILE: metrics-influxdb
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-app-metrics-influxdb
    hostname: edgex-app-metrics-influxdb
    image: edgexfoundry/app-service-configurable:3.1.0
    networks:
      edgex-network: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 59707
      published: "59707"
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
```

I have attached the compose file from running ` make gen no-secty asc-metrics ds-virtual`
[docker-compose.yml.txt](https://github.com/edgexfoundry/community/files/14168941/docker-compose.yml.txt)
