### DISCUSSION TITLE
influxdb-export application service resetting the values and not taking new values from consul registry

### DISCUSSION THREAD

**Discussion by mohammedimrankasab** [edgexfoundry/community#256] [Q&A] [answered]
Hi

we are currently working on containerizing the influxdb-export [app](https://github.com/edgexfoundry/edgex-examples/tree/main/application-services/custom/influxdb-export) service and run it using the docker-compose.

The service is running as expected but there is an observation that whenever we update any custom values like the mqtt broker address using the consul registry it is not reflected and if we restart the application service container then the old value from the configuration.yaml is getting overridden hence not accepting any new values through the consul UI.

```
  app-influxdb-export:
    command:
    - /app-influxdb-export
    - -cp=consul.http://edgex-core-consul:8500
    - --registry
    - -skipVersionCheck=true
    container_name: edgex-app-influxdb-export
    depends_on:
      consul:
        condition: service_started
      core-data:
        condition: service_started
      security-bootstrapper:
        condition: service_started
    entrypoint:
    - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      SECRETSTORE_HOST: edgex-vault
      SERVICE_HOST: edgex-app-influxdb-export
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
    hostname: edgex-app-influxdb-export
    image: edgexfoundry/app-influxdb-export:10.0.0-dev
    networks:
      edge-network: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 59780
      published: "59780"
      protocol: tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - type: volume
      source: edgex-init
      target: /edgex-init
      read_only: true
      volume: {}
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /tmp/edgex/secrets/app-influxdb-export
      target: /tmp/edgex/secrets/app-influxdb-export
      read_only: true
      bind:
        selinux: z
        create_host_path: true
``` 
**Note:** No changes in the code or the configuration.yaml, The only thing is using this code a docker image is built and used as a docker container.

Need help on why the configuration is getting overwritten with default values from configuration.yaml and not taking the latest value from the consul UI.

Thanks
