### DISCUSSION TITLE
Edgex3.1 k3s deployment problem

### DISCUSSION THREAD

**Discussion by Jokerboozp** [edgexfoundry/community#273] [Q&A]
Deployment Environment:
EdgeX 3.1 + k3s

Problem:
When I deploy the core-metadata service using k3s, I encounter the following error:
level=ERROR ts=2024-05-08T06:55:55.303982233Z app=core-data source=httpserver.go:163 msg="Web server failed: listen tcp 10.43.221.201:59880: bind: cannot assign requested address". Additionally, the Consul service is unable to check the health status of core-metadata. However, when I run kubectl get svc -A, it appears that all services are running correctly.

Ignoring this issue and proceeding with the deployment of core-data and core-command results in similar errors. Furthermore, when deploying edgex-ui-go, it fails to recognize any of the services I have deployed.

Attached is my k3s YAML file. Could you please assist me with this issue? Thank you in advance!

- core-metadata
```yml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-08T09:48:51Z"
  labels:
    baetyl-app-name: edgex-core-metadata
  name: edgex-core-metadata
  namespace: baetyl-edge
  resourceVersion: "15697"
  selfLink: /api/v1/namespaces/baetyl-edge/services/edgex-core-metadata
  uid: 8a87264b-7f2c-4f98-8f3b-c415e0acbfa9
spec:
  clusterIP: 10.43.127.129
  ports:
  - name: edgex-core-metadata-59881-tcp
    port: 59881
    protocol: TCP
    targetPort: 59881
  selector:
    baetyl-app-name: edgex-core-metadata
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

- core-common-config
```yml
all-services:
  Writable:
    InsecureSecrets:
      DB:
        SecretName: "redisdb"
        SecretData:
          username: ""
          password: ""
    
    Telemetry:
      Interval: "30s"
      Metrics:
        # Common Security Service Metrics
        SecuritySecretsRequested: false
        SecuritySecretsStored: false
        SecurityConsulTokensRequested: false
        SecurityConsulTokenDuration: false
        SecurityRuntimeSecretTokenDuration: false
        SecurityGetSecretDuration: false
#     Tags: # Contains the service level tags to be attached to all the service's metrics
      #  Gateway: "my-iot-gateway" # Tag must be added here or via Consul Env Override can only change existing value, not added new ones.
      
  Service:
    HealthCheckInterval: "10s"
    ServerBindAddr: "" # Leave blank so default to Host value unless different value is needed.
    MaxResultCount: 1024
    MaxRequestSize: 0 # Not currently used. Defines the maximum size of http request body in bytes
    RequestTimeout: "5s"
    EnableNameFieldEscape: false # The name field escape could allow the system to use special or Chinese characters in the different name fields, including device, profile, and so on.  If the EnableNameFieldEscape is false, some special characters might cause system error.  TODO: This is set to false by default to avoid breaking change and will be removed in EdgeX 4.0
    CORSConfiguration:
      EnableCORS: false
      CORSAllowCredentials: false
      CORSAllowedOrigin: "https://localhost"
      CORSAllowedMethods: "GET, POST, PUT, PATCH, DELETE"
      CORSAllowedHeaders: "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
      CORSExposeHeaders: "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
      CORSMaxAge: 3600

  Registry:
    Host: "localhost"
    Port: 8500
    Type: "consul"
  
  Database:
    Host: "localhost"
    Port: 6379
    Timeout: "5s"
    Type: "redisdb"
  
  MessageBus:
    Protocol: "redis"
    Host: "localhost"
    Port: 6379
    Type: "redis"
    AuthMode: "usernamepassword"  # required for redis MessageBus (secure or insecure).
    SecretName: "redisdb"
    BaseTopicPrefix: "edgex" # prepended to all topics as "edgex/<additional topic levels>
    Optional:
      # Default MQTT Specific options that need to be here to enable environment variable overrides of them
      Qos:  "0" # Quality of Service values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
      KeepAlive: "10" # Seconds (must be 2 or greater)
      Retained: "false"
      AutoReconnect: "true"
      ConnectTimeout: "5" # Seconds
      SkipCertVerify: "false"
      # Additional Default NATS Specific options that need to be here to enable environment variable overrides of them
      Format: "nats"
      RetryOnFailedConnect: "true"
      QueueGroup: ""
      Durable: ""
      AutoProvision: "true"
      Deliver: "new"
      DefaultPubRetryAttempts: "2"
      Subject: "edgex/#" # Required for NATS JetStream only for stream auto-provisioning

app-services:
  Writable:
    StoreAndForward:
      Enabled: false
      RetryInterval: "5m"
      MaxRetryCount: 10
    Telemetry:
      Metrics:
        MessagesReceived: false
        InvalidMessagesReceived: false
        PipelineMessagesProcessed: false # Pipeline IDs are added as the tag for this metric for each pipeline defined
        PipelineMessageProcessingTime: false # Pipeline IDs are added as the tag for this metric for each pipeline defined
        PipelineProcessingErrors: false # Pipeline IDs are added as the tag for this metric for each pipeline defined
        HttpExportSize: false #  Url is added as tag for this metric for each HTTP export defined
        HttpExportErrors: false # Url is added as tag for this metric for each HTTP export defined
        MqttExportSize: false # BrokerAddress and Topic are added as the tag for this metric for each MQTT export defined
        MqttExportErrors: false # BrokerAddress and Topic are added as the tag for this metric for each MQTT export defined
  Clients:
    core-metadata:
      Protocol: "http"
      Host: "localhost"
      Port: 59881
  Trigger:
    Type: "edgex-messagebus"
    SubscribeTopics: "events/#" # Base topic is prepended to this topic when using edgex-messagebus

device-services:
  MaxEventSize: 0 # value 0 represents unlimited  maximum event size that can be sent to message bus or core-data
  Writable:
    Reading:
      ReadingUnits: true
    Telemetry:
      Metrics:
        EventsSent: false
        ReadingsSent: false
        LastConnected: false
  Clients:
    core-metadata:
      Protocol: "http"
      Host: "localhost"
      Port: 59881
  Device:
    DataTransform: true
    MaxCmdOps: 128
    MaxCmdValueLen: 256
    ProfilesDir: "./res/profiles"
    DevicesDir: "./res/devices"
    # ProvisionWatchersDir is omitted here since most Device Services don't use it.
    # Those that do will have it in their private config
    EnableAsyncReadings: true
    AsyncBufferSize: 16
    Labels: []
    Discovery:
      Enabled: false
      Interval: "30s"
```

- consul
![image](https://github.com/edgexfoundry/community/assets/49770457/bb330356-fd8b-44f0-8a61-b1aee569e4e4)
