### DISCUSSION TITLE
Trying to Run the example in a Docker file

### DISCUSSION THREAD

**Discussion by griffinsteffy19** [edgexfoundry/community#279] [Q&A]
So far I have run through the developer example and got it to work but am having trouble getting it to run with the device service inside of a docker container. 

for the compose file, I replaced the example device-rest and device virtual with a new container called device-random that has the exact same configurations, but with port 59999
logs
``` bash
./device-example-c
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="iot_threadpool_alloc (threads: 8 max_jobs: 0 default_priority: -1 affinity: -1)"
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="iot_scheduler_alloc (priority: -1 affinity: -1)"
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="Override config Service/Host = edgex-device-random"
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="Setting LogLevel to DEBUG"
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="Starting device-template device service, version 1.0"
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="EdgeX device SDK for C, version 3.0.1"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service configuration follows:"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Device/DevicesDir="./res/devices""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Device/EventQLength=0"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Device/Labels=[]"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Device/ProfilesDir="./res/profiles""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Driver/TestParam1="X""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/AuthMode="usernamepassword""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/BaseTopicPrefix="edgex""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Disabled=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Host="edgex-redis""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Optional/CertFile="""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Optional/ClientId="device-example""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Optional/KeepAlive=60"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Optional/KeyFile="""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Optional/Qos=0"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Optional/Retained=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Optional/SkipCertVerify=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Port=6379"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Protocol="redis""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/SecretName="redisdb""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="MessageBus/Type="redis""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/Authentication/AuthType="X-Vault-Token""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/DisableScrubSecretsFile=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/Host="localhost""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/Path="device-template/""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/Port=8200"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/Protocol="http""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/RootCaCertPath="""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/SecretsFile="""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/ServerName="""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/TokenFile="/tmp/edgex/secrets/device-template/secrets-token.json""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="SecretStore/Type="vault""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/CORSConfiguration/CORSAllowCredentials=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/CORSConfiguration/CORSAllowedHeaders="Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/CORSConfiguration/CORSAllowedMethods="GET, POST, PUT, PATCH, DELETE""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/CORSConfiguration/CORSAllowedOrigin="https://localhost""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/CORSConfiguration/CORSExposeHeaders="Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/CORSConfiguration/CORSMaxAge=3600"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/CORSConfiguration/EnableCORS=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/HealthCheckInterval="""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/Host="edgex-device-random""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/MaxRequestSize=0"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/Port=59999"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/RequestTimeout="5s""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/ServerBindAddr="""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Service/StartupMsg="device simple started""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Device/DataTransform=true"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Device/Discovery/Enabled=true"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Device/Discovery/Interval=0"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Device/MaxCmdOps=0"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Device/MaxEventSize=0"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Device/UpdateLastConnected=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Driver/TestParam2="Y""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Driver/TestParam3="Z""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/LogLevel="DEBUG""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Telemetry/Interval="30s""
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Telemetry/Metrics/EventsSent=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Telemetry/Metrics/ReadCommandsExecuted=true"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Telemetry/Metrics/ReadingsSent=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Telemetry/Metrics/SecuritySecretsRequested=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Telemetry/Metrics/SecuritySecretsStored=false"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Writable/Telemetry/PublishTopicPrefix="edgex/telemetry""
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="iot_threadpool_alloc (threads: 1 max_jobs: 0 default_priority: -1 affinity: -1)"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Thread iot-1-0 #0 starting"
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="Message Bus is set to Redis streams at edgex-redis:6379"
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="Found core-metadata service at edgex-core-metadata:59881"
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="Processing Device Profiles from ./res/profiles"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Checking existence of DeviceProfile RandNum-Device"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="HTTP response: 404"
level=INFO ts=2024-05-30T16:39:47Z app=device-template msg="Uploading deviceprofile from ./res/profiles/random-generator.yaml"
level=ERROR ts=2024-05-30T16:39:47Z app=device-template msg="Curl failed with code 3 (URL using bad/illegal format or missing URL)"
level=ERROR ts=2024-05-30T16:39:47Z app=device-template msg="Error uploading device profile"
Error: 21: HTTP request failed
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Thread 5 exiting"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Thread 3 exiting"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Thread 2 exiting"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Thread 6 exiting"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Thread 1 exiting"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Thread 7 exiting"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Thread 4 exiting"
level=DEBUG ts=2024-05-30T16:39:47Z app=device-template msg="Thread 0 exiting"
level=DEBUG ts=2024-05-30T16:39:48Z app=device-template msg="Thread 0 exiting"
```

Dockerfile:
``` Dockerfile
FROM arm64v8/ubuntu:jammy AS base

ENV DEBIAN_FRONTEND=nonintercative
RUN apt-get update
RUN apt install -y libcurl4-openssl-dev
RUN apt install -y libmicrohttpd-dev
RUN apt install -y libyaml-dev
RUN apt install -y libcbor-dev
RUN apt install -y libpaho-mqtt-dev
RUN apt install -y uuid-dev
RUN apt install -y libhiredis-dev
RUN apt install -y libcurl4 libcurl4-openssl-dev curl
RUN apt install -y cmake
RUN apt install -y lsb-release apt-transport-https curl gnupg
RUN apt install -y libncurses5-dev
RUN apt install -y git

RUN curl -fsSL https://iotech.jfrog.io/artifactory/api/gpg/key/public | gpg --dearmor -o /usr/share/keyrings/iotech.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/iotech.gpg] https://iotech.jfrog.io/iotech/debian-release $(lsb_release -cs) main" | tee -a /etc/apt/sources.list.d/iotech.list
RUN apt-get update
RUN apt-get install -y iotech-iot-1.5-dev

RUN apt-get install -y inetutils-ping
# clone edgex device sdk
WORKDIR /app
RUN git clone -b v3.0.1 https://github.com/edgexfoundry/device-sdk-c.git

WORKDIR /app/device-sdk-c

RUN make

WORKDIR /app
COPY . /app/example-device-c
WORKDIR /app/example-device-c
ENV CSDK_DIR=../device-sdk-c/build/release/_CPack_Packages/Linux/TGZ/csdk-3.0.1
ENV LD_LIBRARY_PATH=$CSDK_DIR/lib:/opt/iotech/iot/1.5/lib
ENV EDGEX_SECURITY_SECRET_STORE=false

RUN gcc -I$CSDK_DIR/include -I/opt/iotech/iot/1.5/include -L$CSDK_DIR/lib -L/opt/iotech/iot/1.5/lib -o device-example-c template.c -lcsdk -liot
ENTRYPOINT ["./device-example-c"]
```

docker-compose:
``` yaml
#  * Copyright 2023 Intel Corporation.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * EdgeX Foundry, Napa release
#  *******************************************************************************/
#
#
#
# ************************ This is a generated compose file ****************************
#
# DO NOT MAKE CHANGES that are intended to be permanent to EdgeX edgex-compose repo.
#
# Permanent changes can be made to the source compose files located in the compose-builder folder
# at the top level of the edgex-compose repo.
#
# From the compose-builder folder use `make build` to regenerate all standard compose files variations
#
name: edgex
services:
  app-rules-engine:
    container_name: edgex-app-rules-engine
    depends_on:
      consul:
        condition: service_started
      core-data:
        condition: service_started
    environment:
      EDGEX_PROFILE: rules-engine
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-app-rules-engine
    hostname: edgex-app-rules-engine
    image: edgexfoundry/app-service-configurable-arm64:3.1.0
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59701
        published: "59701"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  consul:
    command:
      - agent
      - -ui
      - -bootstrap
      - -server
      - -client
      - 0.0.0.0
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    image: hashicorp/consul:1.16.2
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8500
        published: "8500"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - type: volume
        source: consul-config
        target: /consul/config
        volume: {}
      - type: volume
        source: consul-data
        target: /consul/data
        volume: {}
  core-command:
    container_name: edgex-core-command
    depends_on:
      consul:
        condition: service_started
      core-metadata:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      EXTERNALMQTT_URL: tcp://edgex-mqtt-broker:1883
      SERVICE_HOST: edgex-core-command
    hostname: edgex-core-command
    image: edgexfoundry/core-command-arm64:3.1.0
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59882
        published: "59882"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  core-common-config-bootstrapper:
    container_name: edgex-core-common-config-bootstrapper
    depends_on:
      consul:
        condition: service_started
    environment:
      ALL_SERVICES_DATABASE_HOST: edgex-redis
      ALL_SERVICES_MESSAGEBUS_HOST: edgex-redis
      ALL_SERVICES_REGISTRY_HOST: edgex-core-consul
      APP_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      DEVICE_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      EDGEX_SECURITY_SECRET_STORE: "false"
    hostname: edgex-core-common-config-bootstrapper
    image: edgexfoundry/core-common-config-bootstrapper-arm64:3.1.0
    networks:
      edgex-network: null
    read_only: true
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  core-data:
    container_name: edgex-core-data
    depends_on:
      consul:
        condition: service_started
      core-metadata:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-data
    hostname: edgex-core-data
    image: edgexfoundry/core-data-arm64:3.1.0
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59880
        published: "59880"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  core-metadata:
    container_name: edgex-core-metadata
    depends_on:
      consul:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-metadata
    hostname: edgex-core-metadata
    image: edgexfoundry/core-metadata-arm64:3.1.0
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59881
        published: "59881"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  database:
    container_name: edgex-redis
    hostname: edgex-redis
    image: redis:7.0.14-alpine
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 6379
        published: "6379"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume: {}
  # device-rest:
  #   container_name: edgex-device-rest
  #   depends_on:
  #     consul:
  #       condition: service_started
  #     core-data:
  #       condition: service_started
  #     core-metadata:
  #       condition: service_started
  #   environment:
  #     EDGEX_SECURITY_SECRET_STORE: "false"
  #     SERVICE_HOST: edgex-device-rest
  #   hostname: edgex-device-rest
  #   image: edgexfoundry/device-rest-arm64:3.1.0
  #   networks:
  #     edgex-network: null
  #   ports:
  #     - mode: ingress
  #       host_ip: 127.0.0.1
  #       target: 59986
  #       published: "59986"
  #       protocol: tcp
  #   read_only: true
  #   restart: always
  #   security_opt:
  #     - no-new-privileges:true
  #   user: 2002:2001
  #   volumes:
  #     - type: bind
  #       source: /etc/localtime
  #       target: /etc/localtime
  #       read_only: true
  #       bind:
  #         create_host_path: true
  # device-virtual:
  #   container_name: edgex-device-virtual
  #   depends_on:
  #     consul:
  #       condition: service_started
  #     core-data:
  #       condition: service_started
  #     core-metadata:
  #       condition: service_started
  #   environment:
  #     EDGEX_SECURITY_SECRET_STORE: "false"
  #     SERVICE_HOST: edgex-device-virtual
  #   hostname: edgex-device-virtual
  #   image: edgexfoundry/device-virtual-arm64:3.1.0
  #   networks:
  #     edgex-network: null
  #   ports:
  #     - mode: ingress
  #       host_ip: 127.0.0.1
  #       target: 59900
  #       published: "59900"
  #       protocol: tcp
  #   read_only: true
  #   restart: always
  #   security_opt:
  #     - no-new-privileges:true
  #   user: 2002:2001
  #   volumes:
  #     - type: bind
  #       source: /etc/localtime
  #       target: /etc/localtime
  #       read_only: true
  #       bind:
  #         create_host_path: true
  device-random:
    container_name: edgex-device-random
    depends_on:
      consul:
        condition: service_started
      core-data:
        condition: service_started
      core-metadata:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-device-random
    hostname: edgex-device-random
    image: cmprandommodule:0.0.2
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59999
        published: "59999"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  rules-engine:
    container_name: edgex-kuiper
    depends_on:
      database:
        condition: service_started
    environment:
      CONNECTION__EDGEX__REDISMSGBUS__PORT: "6379"
      CONNECTION__EDGEX__REDISMSGBUS__PROTOCOL: redis
      CONNECTION__EDGEX__REDISMSGBUS__SERVER: edgex-redis
      CONNECTION__EDGEX__REDISMSGBUS__TYPE: redis
      EDGEX__DEFAULT__PORT: "6379"
      EDGEX__DEFAULT__PROTOCOL: redis
      EDGEX__DEFAULT__SERVER: edgex-redis
      EDGEX__DEFAULT__TOPIC: edgex/rules-events
      EDGEX__DEFAULT__TYPE: redis
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__RESTPORT: "59720"
    hostname: edgex-kuiper
    image: lfedge/ekuiper:1.11.4-alpine
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59720
        published: "59720"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: kuiper:kuiper
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: kuiper-data
        target: /kuiper/data
        volume: {}
      - type: volume
        source: kuiper-etc
        target: /kuiper/etc
        volume: {}
      - type: volume
        source: kuiper-log
        target: /kuiper/log
        volume: {}
      - type: volume
        source: kuiper-plugins
        target: /kuiper/plugins
        volume: {}
  support-notifications:
    container_name: edgex-support-notifications
    depends_on:
      consul:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-support-notifications
    hostname: edgex-support-notifications
    image: edgexfoundry/support-notifications-arm64:3.1.0
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59860
        published: "59860"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  support-scheduler:
    container_name: edgex-support-scheduler
    depends_on:
      consul:
        condition: service_started
      database:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      INTERVALACTIONS_SCRUBAGED_HOST: edgex-core-data
      INTERVALACTIONS_SCRUBPUSHED_HOST: edgex-core-data
      SERVICE_HOST: edgex-support-scheduler
    hostname: edgex-support-scheduler
    image: edgexfoundry/support-scheduler-arm64:3.1.0
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59861
        published: "59861"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  ui:
    container_name: edgex-ui-go
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-ui-go
    hostname: edgex-ui-go
    image: edgexfoundry/edgex-ui-arm64:3.1.0
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        target: 4000
        published: "4000"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
networks:
  edgex-network:
    name: edgex_edgex-network
    driver: bridge
volumes:
  consul-config:
    name: edgex_consul-config
  consul-data:
    name: edgex_consul-data
  db-data:
    name: edgex_db-data
  kuiper-data:
    name: edgex_kuiper-data
  kuiper-etc:
    name: edgex_kuiper-etc
  kuiper-log:
    name: edgex_kuiper-log
  kuiper-plugins:
    name: edgex_kuiper-plugins
```

when I run the curl command standalone I get this...
``` bash
$ curl -X 'PUT' \
  'http://edgex-core-metadata:59881/api/v3/deviceprofile/uploadfile' \
  -H 'accept: application/json' \
  -H 'X-Correlation-ID: 14a42ea6-c394-41c3-8bcd-a29b9f5e6835' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@/app/example-device-c/res/profiles/random-generator.yaml;type=application/x-yaml'> > > > > 
{"apiVersion":"v3","message":"fail to query device profile by name RandNum-Device","statusCode":404}
```

**Comment by cloudxxx8** [comment]
you are using v3.1 for other services, so please try to use sdk v3.1, not v3.0
we didn't implement common config in v3.0

**Comment by griffinsteffy19** [comment]
@cloudxxx8 Thank you for the help. I'm sure that fixes that issue, but when I build the sdk v3.1 I get outputs to the release folder called 3.0.2. Is that expected? If I update the $CSDK_DIR to the new location (using 3.0.2), it can seem to find the configuration file. Are there changes to the example on the wiki that are needed with using 3.1.0?

``` bash
$ ./template
level=INFO ts=2024-05-31T13:08:26Z app=device-template msg="iot_threadpool_alloc (threads: 8 max_jobs: 0 default_priority: -1 affinity: -1)"
level=INFO ts=2024-05-31T13:08:26Z app=device-template msg="iot_scheduler_alloc (priority: -1 affinity: -1)"
level=ERROR ts=2024-05-31T13:08:26Z app=device-template msg="Cant open file (null)"
level=ERROR ts=2024-05-31T13:08:26Z app=device-template msg="Unable to load common config file: Unable to open configuration file"
Error: 1: Unable to open configuration file
```

Files
![image](https://github.com/edgexfoundry/community/assets/94927793/0ab3ed64-9eb0-4ca4-b30f-6ddd5f742b57)

configuration.yaml
``` yaml
Writable:
  LogLevel: DEBUG
  Reading:
    ReadingUnits: true
  Telemetry:
    Metrics:
      # All service's custom metric names must be present in this list. All common metric names are in the Common Config
      ReadCommandsExecuted: true
Service:
  Host: "127.0.0.1"
  Port: 59999 # Device service are assigned the 599xx range
  StartupMsg: device simple started

Clients:
  core-metadata:
    Host: "edgex-core-metadata"
    Port: 59881

MessageBus:
  Protocol: redis
  Host: "edgex-redis"
  Port: 6379
  Type: redis
  AuthMode: "usernamepassword"  # required for redis messagebus (secure or insecure)
  SecretName: redisdb
  Optional:
    ClientId: device-example

# Example overriding of Common Config settings
Device:
  AsyncBufferSize: 1
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"
  # Only needed if device service implements auto provisioning
  ProvisionWatchersDir: ./res/provisionwatchers
# Example structured custom configuration
SimpleCustom:
  OnImageLocation: ./res/on.png
  OffImageLocation: ./res/off.jpg
  Writable:
    DiscoverSleepDurationSecs: 10
```

I pulled template.c from the tag v3.1.0, and am running it directly
