### DISCUSSION TITLE
Need help !: Not able to perform influx db export

### DISCUSSION THREAD

**Discussion by M0hanrajp** [edgexfoundry/community#299] [Q&A] [answered]
**[ Issue ]**

Not able to send device-virtual metrics data to Influx db !

**[ Description ]**

* Execute simple scenario of sending device-virtual metrics to influx db and UI(localhost:8086) should indicate metrics.
* Export to influx db is performed by referring [metrics-influxdb
](https://docs.edgexfoundry.org/3.1/microservices/application/AppServiceConfigurable/#metrics-influxdb)

I have included environment variables, but I don't see device virtual sending any metrics. 

device-virtual configurations: (full configurations provided in the attached .yml file)
```yml
  device-virtual:
...
...
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-device-virtual
      WRITABLE_TELEMETRY_INTERVAL: "3s"
      WRITABLE_TELEMETRY_METRICS_EVENTSSENT: "true"
      WRITABLE_TELEMETRY_METRICS_READINGSSSENT: "true"
      WRITABLE_LOGLEVEL: TRACE
    hostname: edgex-device-virtual
    image: edgexfoundry/device-virtual:3.1.1
...
```
device-virtual logs:
```bash
edgex-device-virtual  | level=INFO ts=2024-08-05T14:05:06.678514465Z app=device-virtual source=messaging.go:104 msg="Connected to redis Message Bus @ redis://edgex-redis:6379 with AuthMode='usernamepassword'"
# Publish 0 metrics to the 'edgex/telemetry/device-virtual
edgex-device-virtual  | level=DEBUG ts=2024-08-05T14:05:36.6855458Z app=device-virtual source=reporter.go:195 msg="Publish 0 metrics to the 'edgex/telemetry/device-virtual' base topic"
```
According to me, if I'm able to send metric data to app-metrics-influx then I would be sending data to Influx db.

### Please help on this ! 

---
Thanks.
[docker-compose.txt](https://github.com/user-attachments/files/16499302/docker-compose.txt)

**Comment by cloudxxx8** [comment]
please use the /api/v3/config to confirm the environment variable setting takes effect.
if you started the services without these envronment variables before, the configs are pushed to the config provider (Consul by default), and they will take priority.
You need to add "-o" flag to the service or modify the config from the config provider.
If it's Consul, try to use its UI to modifyt http://ip-address:8500

**Reply by M0hanrajp** [reply]
Can you please check below comment ? Thanks

**Comment by M0hanrajp** [comment]
used /api/v3/config for device-virtual and the values were not set:
```bash
      "Telemetry": {
        "Interval": "30s",
        "Metrics": {
          "EventsSent": false,
          "LastConnected": false,
          "ReadingsSent": false,
          "SecurityConsulTokenDuration": false,
          "SecurityConsulTokensRequested": false,
          "SecurityGetSecretDuration": false,
          "SecurityRuntimeSecretTokenDuration": false,
          "SecuritySecretsRequested": false,
          "SecuritySecretsStored": false
        },
        "Tags": null
      }
    }
  },
  "serviceName": "device-virtual"
}
```
So I added overwrite and cp & config provider for device-virtual in the compose file:
```yml
  device-virtual:
    command:
    - cp
    - --overwrite
    container_name: edgex-device-virtual
    depends_on:
      consul:
        condition: service_started
        required: true
      core-data:
        condition: service_started
        required: true
      core-metadata:
        condition: service_started
        required: true
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-device-virtual
      WRITABLE_TELEMETRY_INTERVAL: "5s"
      WRITABLE_TELEMETRY_METRICS_EVENTSSENT: "true"
      WRITABLE_TELEMETRY_METRICS_READINGSSSENT: "true"
      WRITABLE_LOGLEVEL: TRACE
      EDGEX_CONFIG_PROVIDER: consul.http://edgex-core-consul:8500
```
When used /api/v3/config again the values are not set and there is no metrics published.
```bash
edgex-device-virtual  | level=DEBUG ts=2024-08-06T10:39:36.031538196Z app=device-virtual source=reporter.go:195 msg="Publish 0 metrics to the 'edgex/telemetry/device-virtual' base topic"
```
### I'm I missing anything ?

**Reply by cloudxxx8** [reply]
your command setting is wrong.  please try:
```
    command:
      - -cp=consul.http://edgex-core-consul:8500
      - --registry
      - -o
```

**Reply by M0hanrajp** [reply]
I used the same configuration:
```yml
  device-virtual:
    command:
    - -cp=consul.http://edgex-core-consul:8500
    - --registry
    - -o
    container_name: edgex-device-virtual
    depends_on:
      consul:
        condition: service_started
        required: true
      core-data:
        condition: service_started
        required: true
      core-metadata:
        condition: service_started
        required: true
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-device-virtual
      WRITABLE_TELEMETRY_INTERVAL: 5s
      WRITABLE_TELEMETRY_METRICS_EVENTSSENT: TRUE
      WRITABLE_TELEMETRY_METRICS_LASTCONNECTED: TRUE
      WRITABLE_TELEMETRY_METRICS_READINGSSSENT: TRUE
      WRITABLE_LOGLEVEL: TRACE
 ```
But there are no metrics published:
```bash
edgex-device-virtual  | level=DEBUG ts=2024-08-07T06:58:43.081496296Z app=device-virtual source=reporter.go:195 msg="Publish 0 metrics to the 'edgex/telemetry/device-virtual' base topic"
```
api/v3/config also returns false for all the settings.
