### DISCUSSION TITLE
GET/PUT command with MQTT-test-device does not work, 500 response reported

### DISCUSSION THREAD

**Discussion by M0hanrajp** [edgexfoundry/community#308] [Q&A] [answered]
Please note this discussion is created to address MQTT-test-device issue.

**[Issue]:**

### GET/PUT command with MQTT-test-device does not work with any of the test devices:

randfloat32: 
```json
 curl http://localhost:59882/api/v3/device/name/MQTT-test-device/randfloat32 | json_pp

{
   "apiVersion" : "v3",
   "message" : "request failed, status code: 500, err: {\"apiVersion\":\"v3\",\"message\":\"error reading Regex DeviceResource(s) randfloat32 for MQTT-test-device -\\u003e can not fetch command response: method=get source=randfloat32\",\"statusCode\":500}",
   "statusCode" : 500
}
```

randfloat64:
```json
 curl http://localhost:59882/api/v3/device/name/MQTT-test-device/randfloat64 | json_pp

{
   "apiVersion" : "v3",
   "message" : "request failed, status code: 500, err: {\"apiVersion\":\"v3\",\"message\":\"error reading Regex DeviceResource(s) randfloat64 for MQTT-test-device -\\u003e can not fetch command response: method=get source=randfloat64\",\"statusCode\":500}",
   "statusCode" : 500
}
```
ping:
```json
curl http://localhost:59882/api/v3/device/name/MQTT-test-device/ping | json_pp

{
   "apiVersion" : "v3",
   "message" : "request failed, status code: 500, err: {\"apiVersion\":\"v3\",\"message\":\"error reading Regex DeviceResource(s) ping for MQTT-test-device -\\u003e can not fetch command response: method=get source=ping\",\"statusCode\":500}",
   "statusCode" : 500
}
```
message:
```json
curl http://localhost:59882/api/v3/device/name/MQTT-test-device/message | json_pp

{
   "apiVersion" : "v3",
   "message" : "request failed, status code: 500, err: {\"apiVersion\":\"v3\",\"message\":\"error reading Regex DeviceResource(s) message for MQTT-test-device -\\u003e can not fetch command response: method=get source=message\",\"statusCode\":500}",
   "statusCode" : 500
}
```
json:
```json
curl http://localhost:59882/api/v3/device/name/MQTT-test-device/json | json_pp

{
   "apiVersion" : "v3",
   "message" : "request failed, status code: 500, err: {\"apiVersion\":\"v3\",\"message\":\"error reading Regex DeviceResource(s) json for MQTT-test-device -\\u003e can not fetch command response: method=get source=json\",\"statusCode\":500}",
   "statusCode" : 500
}
```
allValues:
```json
curl http://localhost:59882/api/v3/device/name/MQTT-test-device/allValues | json_pp

{
   "apiVersion" : "v3",
   "message" : "request failed, status code: 500, err: {\"apiVersion\":\"v3\",\"message\":\"error reading DeviceCommand allValues for MQTT-test-device -\\u003e can not fetch command response: method=get source=randfloat32\",\"statusCode\":500}",
   "statusCode" : 500
}
```
---

### Device-mqtt side logs:

```bash
edgex-device-mqtt  | level=DEBUG source=driver.go:137 msg="Publish command: "
edgex-device-mqtt  | level=ERROR source=driver.go:111 msg="Handle read commands failed: can not fetch command response: method=get source=randfloat32"
edgex-device-mqtt  | level=ERROR source=restrouter.go:159 X-Correlation-ID=2f181443-66e9-40b1-9405-70bc48632e9c msg="error reading Regex DeviceResource(s) randfloat32 for MQTT-test-device -> can not fetch command response: method=get source=randfloat32"
edgex-device-mqtt  | level=DEBUG source=restrouter.go:160 X-Correlation-ID=2f181443-66e9-40b1-9405-70bc48632e9c msg="[github.com/edgexfoundry/device-sdk-go/v3@v3.1.1/internal/application/command.go]-github.com/edgexfoundry/device-sdk-go/v3/internal/application.GetCommand(line 61):  -> [github.com/edgexfoundry/device-sdk-go/v3@v3.1.1/internal/application/command.go]-github.com/edgexfoundry/device-sdk-go/v3/internal/application.readDeviceResourcesRegex(line 194): error reading Regex DeviceResource(s) randfloat32 for MQTT-test-device -> [github.com/edgexfoundry/device-mqtt-go/internal/driver/driver.go]-github.com/edgexfoundry/device-mqtt-go/internal/driver.(*Driver).handleReadCommandRequest(line 142): can not fetch command response: method=get source=randfloat32"
...
...
edgex-device-mqtt  | level=DEBUG source=driver.go:137 msg="Publish command: "
edgex-device-mqtt  | level=DEBUG source=reporter.go:195 msg="Publish 0 metrics to the 'edgex/telemetry/device-mqtt' base topic"
edgex-device-mqtt  | level=DEBUG source=manager.go:123 msg="Reported metrics..."
edgex-device-mqtt  | level=ERROR source=driver.go:111 msg="Handle read commands failed: can not fetch command response: method=get source=randfloat64"
edgex-device-mqtt  | level=ERROR source=restrouter.go:159 X-Correlation-ID=bb54c944-6665-4a55-ae64-7c1ae114c8e6 msg="error reading Regex DeviceResource(s) randfloat64 for MQTT-test-device -> can not fetch command response: method=get source=randfloat64"
edgex-device-mqtt  | level=DEBUG source=restrouter.go:160 X-Correlation-ID=bb54c944-6665-4a55-ae64-7c1ae114c8e6 msg="[github.com/edgexfoundry/device-sdk-go/v3@v3.1.1/internal/application/command.go]-github.com/edgexfoundry/device-sdk-go/v3/internal/application.GetCommand(line 61):  -> [github.com/edgexfoundry/device-sdk-go/v3@v3.1.1/internal/application/command.go]-github.com/edgexfoundry/device-sdk-go/v3/internal/application.readDeviceResourcesRegex(line 194): error reading Regex DeviceResource(s) randfloat64 for MQTT-test-device -> [github.com/edgexfoundry/device-mqtt-go/internal/driver/driver.go]-github.com/edgexfoundry/device-mqtt-go/internal/driver.(*Driver).handleReadCommandRequest(line 142): can not fetch command response: method=get source=randfloat64"
...
...
edgex-device-mqtt  | level=DEBUG source=driver.go:137 msg="Publish command: "
edgex-device-mqtt  | level=ERROR source=driver.go:111 msg="Handle read commands failed: can not fetch command response: method=get source=message"
edgex-device-mqtt  | level=ERROR source=restrouter.go:159 X-Correlation-ID=ff7d82e9-7767-4a5f-a023-94e1328d81b3 msg="error reading Regex DeviceResource(s) message for MQTT-test-device -> can not fetch command response: method=get source=message"
edgex-device-mqtt  | level=DEBUG source=restrouter.go:160 X-Correlation-ID=ff7d82e9-7767-4a5f-a023-94e1328d81b3 msg="[github.com/edgexfoundry/device-sdk-go/v3@v3.1.1/internal/application/command.go]-github.com/edgexfoundry/device-sdk-go/v3/internal/application.GetCommand(line 61):  -> [github.com/edgexfoundry/device-sdk-go/v3@v3.1.1/internal/application/command.go]-github.com/edgexfoundry/device-sdk-go/v3/internal/application.readDeviceResourcesRegex(line 194): error reading Regex DeviceResource(s) message for MQTT-test-device -> [github.com/edgexfoundry/device-mqtt-go/internal/driver/driver.go]-github.com/edgexfoundry/device-mqtt-go/internal/driver.(*Driver).handleReadCommandRequest(line 142): can not fetch command response: method=get source=message"
...
...
edgex-device-mqtt  | level=DEBUG source=driver.go:137 msg="Publish command: "
edgex-device-mqtt  | level=ERROR source=driver.go:111 msg="Handle read commands failed: can not fetch command response: method=get source=json"
edgex-device-mqtt  | level=ERROR source=restrouter.go:159 X-Correlation-ID=45c8b828-d597-4ec2-9c7b-e8b7698938fc msg="error reading Regex DeviceResource(s) json for MQTT-test-device -> can not fetch command response: method=get source=json"
edgex-device-mqtt  | level=DEBUG source=restrouter.go:160 X-Correlation-ID=45c8b828-d597-4ec2-9c7b-e8b7698938fc msg="[github.com/edgexfoundry/device-sdk-go/v3@v3.1.1/internal/application/command.go]-github.com/edgexfoundry/device-sdk-go/v3/internal/application.GetCommand(line 61):  -> [github.com/edgexfoundry/device-sdk-go/v3@v3.1.1/internal/application/command.go]-github.com/edgexfoundry/device-sdk-go/v3/internal/application.readDeviceResourcesRegex(line 194): error reading Regex DeviceResource(s) json for MQTT-test-device -> [github.com/edgexfoundry/device-mqtt-go/internal/driver/driver.go]-github.com/edgexfoundry/device-mqtt-go/internal/driver.(*Driver).handleReadCommandRequest(line 142): can not fetch command response: method=get source=json"
...
...
# similar error observed further.
```

**Comment by somashekhar-bm** [comment, marked as answer]
**Steps to set up and simulate an MQTT device using EdgeX Foundry:**

1. **Generate the `docker-compose.yml` file (this includes `mqtt-broker`)**:
   ```bash
   $ cd compose-builder
   $ make gen ds-mqtt mqtt-broker mqtt-verbose no-secty ui
   $ sudo docker compose up -d
   ```

2. **Create a Device Profile in EdgeX UI**:
   - Name: "my-custom-device-profile"
   - Manufacturer: "iot"
   - Model: "MQTT-DEVICE"
   - Description: "Test device profile"
   - Labels:
     - "mqtt"
     - "test"
   - Device Resources:
     ```yaml
     deviceResources:
       - name: randnum
         isHidden: true
         description: "device random number"
         properties:
           valueType: "Float32"
           readWrite: "R"
       - name: ping
         isHidden: true
         description: "device awake"
         properties:
           valueType: "String"
           readWrite: "R"
       - name: message
         isHidden: false
         description: "device message"
         properties:
           valueType: "String"
           readWrite: "RW"
       - name: json
         isHidden: false
         description: "JSON message"
         properties:
           valueType: "Object"
           readWrite: "RW"
           mediaType: "application/json"
     ```
   - Device Commands:
     ```yaml
     deviceCommands:
       - name: values
         readWrite: "R"
         isHidden: false
         resourceOperations:
           - { deviceResource: "randnum" }
           - { deviceResource: "ping" }
           - { deviceResource: "message" }
     ```

3. **Create an MQTT Device in EdgeX UI**:
   ```yaml
   deviceList:
     - name: "my-custom-device"
       profileName: "my-custom-device-profile"
       description: "MQTT device created for test purpose"
       labels: [ "MQTT", "test" ]
       protocols:
         mqtt:
           CommandTopic: "command/my-custom-device"
       autoEvents:
         - interval: "30s"
           onChange: false
           sourceName: "message"
   ```

4. **Create and Run an MQTT Device Simulator**:
   - Create a JavaScript file named `mock-device.js` with the following content:
     ```javascript
     function getRandomFloat(min, max) {
         return Math.random() * (max - min) + min;
     }

     const deviceName = "my-custom-device";
     let message = "test-message";
     let json = {"name" : "My JSON"};

     // DataSender sends async value to MQTT broker every 15 seconds
     schedule('*/15 * * * * *', ()=>{
         var data = {};
         data.randnum = getRandomFloat(25,29).toFixed(1);
         data.ping = "pong";
         data.message = "Hello World";

         publish('incoming/data/my-custom-device/values', JSON.stringify(data));
     });

     // CommandHandler receives commands and sends response to MQTT broker
     subscribe("command/my-custom-device/#", (topic, val) => {
         const words = topic.split('/');
         var cmd = words[2];
         var method = words[3];
         var uuid = words[4];
         var response = {};
         var data = val;

         if (method == "set") {
             switch(cmd) {
                 case "message":
                     message = data[cmd];
                     break;
                 case "json":
                     json = data[cmd];
                     break;
             }
         } else {
             switch(cmd) {
                 case "ping":
                     response.ping = "pong";
                     break;
                 case "message":
                     response.message = message;
                     break;
                 case "randnum":
                     response.randnum = 12.123;
                     break;
                 case "json":
                     response.json = json;
                     break;
             }
         }
         var sendTopic = "command/response/" + uuid;
         publish(sendTopic, JSON.stringify(response));
     });
     ```

   - Create a directory `mqtt-scripts` and move `mock-device.js` to it:
     ```bash
     $ mv mock-device.js /path/to/mqtt-scripts
     ```

   - Run the following command to start the simulator:
     ```bash
     $ docker run --rm --name=mqtt-scripts -v /path/to/mqtt-scripts:/scripts --network host -e LOG_LEVEL=DEBUG dersimn/mqtt-scripts --dir /scripts --verbose
     ```

   - The MQTT scripts will show logs like:
     ```
     2022-08-12 09:52:42.086 <info>  mqtt-scripts 1.2.2 starting
     2022-08-12 09:52:42.227 <info>  mqtt connected mqtt://127.0.0.1
     2022-08-12 09:52:42.733 <info>  /scripts/mock-device.js loading
     ```
