### DISCUSSION TITLE
[Odessa] Oops!!! xxxx  service is unavailable!

### DISCUSSION THREAD

**Discussion by yqhsmile** [edgexfoundry/community#346] [Q&A]
Odessa ui always makes the following errors:
```
Svc Unavailable
**Oops!!! scheduler service is unavailable!**
This could be a network reason, or it could be that the scheduler microservice is not running, make sure there is no network problem or that the scheduler service is already running!

EdgeXFoundry uses a microservices architecture, each service is running independently, please make sure that the current service is already running, if you have manually started the service, click the Refresh button.


Svc Unavailable
**Oops!!! rule engine service is unavailable!**
This could be a network reason, or it could be that the rule engine microservice is not running, make sure there is no network problem or that the rule engine service is already running!

EdgeXFoundry uses a microservices architecture, each service is running independently, please make sure that the current service is already running, if you have manually started the service, click the Refresh button.


Svc Unavailable
**Oops!!! registry center service is unavailable!**
This could be a network reason, or it could be that the registry center microservice is not running, make sure there is no network problem or that the registry center service is already running!

EdgeXFoundry uses a microservices architecture, each service is running independently, please make sure that the current service is already running, if you have manually started the service, click the Refresh button.

```
![image](https://github.com/user-attachments/assets/fad84da9-a1d3-41ce-a6d9-24e634fac891)
![image](https://github.com/user-attachments/assets/7ff7a0c2-9816-48b8-a561-c389886126a9)
![image](https://github.com/user-attachments/assets/106bf192-3709-416b-b25e-58b3900bb58b)

error logs in edgex-ui-go:
```
2025/05/14 14:52:47 http: proxy error: dial tcp 172.19.0.12:59861: connect: connection refused

/rules-engine/ping

2025/05/14 14:55:59 http: proxy error: dial tcp: lookup edgex-kuiper on 127.0.0.11:53: no such host

/support-scheduler/api/v3/ping

2025/05/14 14:56:12 http: proxy error: dial tcp 172.19.0.12:59861: connect: connection refused

/rules-engine/ping

2025/05/14 14:58:03 http: proxy error: dial tcp: lookup edgex-kuiper on 127.0.0.11:53: no such host

/core-data/api/v3/ping

/core-data/api/v3/ping

/support-scheduler/api/v3/ping

2025/05/14 15:11:29 http: proxy error: dial tcp 172.19.0.12:59861: connect: connection refused

/rules-engine/ping

2025/05/14 15:11:31 http: proxy error: dial tcp: lookup edgex-kuiper on 127.0.0.11:53: no such host
```

And I found that there is such a problem in cmd/edgex-ui-server/res/docker/configuration.yaml:

![image](https://github.com/user-attachments/assets/2570c1ec-3501-44e0-bd22-84662787e3e4)

Registry config is error ????  Why is it still consul ???  How to solve the three problems mentioned above???

![image](https://github.com/user-attachments/assets/7adf26cf-6b31-474c-b28c-096ca15fa825)

Also, the ports here are different in cmd/edgex-ui-server/res/docker/configuration.yaml  and docker-compose.yml，I changed 59863 in docker-compose.yml to 59861， but it still reports the three errors mentioned above.

Is there any problem with the Odessa version? How to solve it?

@judehung @cloudxxx8 @FelixTing @weichou1229

**Comment by cloudxxx8** [comment]
It looks like there are still lots of to do in edgex-ui.
Aside from the edgex-ui, do you see any issues for other services?

Please open the related issues to edgex-ui-go and see if there is any volunteer could help update it.

**Reply by yqhsmile** [reply]
Aside from the edgex-ui,  Just these three errors！

I changed 59863 in docker-compose.yml to 59861， but it still reports the three errors mentioned above.

related issues：
[https://github.com/edgexfoundry/edgex-ui-go/issues/769](url)

**Reply by cloudxxx8** [reply]
What are the three issues?  I saw they all belong to edgex-ui.

**Reply by yqhsmile** [reply]
Yes

**Reply by clint456** [reply]
May be you can try `make clean` or `docker compose -f docker-compose down --volume` to delete volume mounted in local, i recently found the same problem, because i  git checkout `v3.1`  to `v4.0` and  did not clean the volume.

**Reply by yqhsmile** [reply]
I tried it, rule engine service is available! 
But others didn't work very well！

**Reply by yqhsmile** [reply]
This modification can solve the problem in [edgex-ui-go](https://github.com/edgexfoundry/edgex-ui-go/tree/main):

cmd/edgex-ui-server/res/docker/configuration.yaml
```
Clients:
    ......
    support-scheduler:
        Protocol: http
        Host: edgex-support-scheduler
        Port: 59863
        SecurityOptions:
            Mode: ""
            OpenZitiController: "openziti:1280"

Registry:
    Host: edgex-core-keeper
    Port: 59890
    Type: keeper
    ConfigRegistryStem: edgex/
    ServiceVersion: 'v3'
```

cmd/edgex-ui-server/res/configuration.yaml
```
Clients:
    ......
    support-scheduler:
        Protocol: http
        Host: localhost
        Port: 59863
        SecurityOptions:
            Mode: ""
            OpenZitiController: "openziti:1280"

Registry:
    Host: localhost
    Port: 59890
    Type: keeper
    ConfigRegistryStem: edgex/
    ServiceVersion: 'v3'
```

Regenerate Docker image!


But Support Scheduler cannot be used.
Because the underlying interface has changed below：

old：
<img width="752" alt="c28a5527ac8519ffd78ccea313e059a" src="https://github.com/user-attachments/assets/f4ace13b-f997-408c-95a0-6c191ca753dd" />

new：
<img width="541" alt="41a9f7caa19234383693d547da9490f" src="https://github.com/user-attachments/assets/9cc4707b-37fe-47f1-a126-9769a7b65e87" />

In addition, edgex-ui also  is old!
![image](https://github.com/user-attachments/assets/7684fcb6-9751-4d66-9da9-7404ffd3b4eb)

Please upgrade as soon as possible！
