### DISCUSSION TITLE
Common serialization format for device configurations

### DISCUSSION THREAD

**Discussion by farshidtz** [edgexfoundry/community#4] [Ideas]
A device service can have four types of configuration files:
- Server configurations (TOML/JSON?)
- Device(s) configurations (TOML/JSON)
- Profile(s) configurations (YAML/JSON)
- Provision Watcher (JSON)

(The list of supported serializations may not be complete.)

This is all very confusing and difficult to work with.

Can YAML be used as a common serialization for all config files?
If TOML is the preferred format (although nowadays not as common), why the device profile and provision watcher are different?

**Comment by iain-anderson** [comment]
Ideally these options would be simplified, however it is difficult to obtain agreement on what single format should be adopted. From our (commercial) perspective we'd like to see all of these files in JSON.

**Reply by lenny-goodell** [reply]
JSON is get for APIs, but not the best for files that are manually edited. This is why we have YAML and TOML for the static files. I could see standardizing all the static files to YAML or TOML, probably YAML since it is more widely used.

**Reply by iain-anderson** [reply]
Well, you choose your poison. JSON has quoting inconveniences; TOML's syntax for object arrays is a little clumsy; YAML invokes the holy war over indendation/spacing as syntax etc

**Comment by farshidtz** [comment]
For reference, adding a snippet of Device MQTT config in different serialization formats;

```toml
[Writable]
LogLevel = "INFO"
  # InsecureSecrets are required for when Redis is used for message bus
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""
    [Writable.InsecureSecrets.MQTT]
    path = "credentials"
      [Writable.InsecureSecrets.MQTT.Secrets]
      username = ""
      password = ""
  [Writable.Reading]
  ReadingUnits = true
  [Writable.Telemetry]
  Interval = "30s"
  PublishTopicPrefix  = "edgex/telemetry" # /<service-name>/<metric-name> will be added to this Publish Topic prefix
    [Writable.Telemetry.Metrics] # All service's metric names must be present in this list.
    # Device SDK provided Service Metrics
    EventsSent = false
    ReadingsSent = false
    # Common Security Service Metrics
    SecuritySecretsRequested = false
    SecuritySecretsStored = false
    SecurityConsulTokensRequested = false
    SecurityConsulTokenDuration = false
    [Writable.Telemetry.Tags] # Contains the service level tags to be attached to all the service's metrics
#    Gateway="my-iot-gateway" # Tag must be added here or via Consul Env Override can only chnage existing value, not added new ones.
```

```yaml
Writable:
  LogLevel: INFO
  # InsecureSecrets are required for when Redis is used for message bus
  InsecureSecrets:
    DB:
      path: redisdb
      Secrets:
        username: ''
        password: ''
    MQTT:
      path: credentials
      Secrets:
        username: ''
        password: ''
  Reading:
    ReadingUnits: true
  Telemetry:
    Interval: 30s
    PublishTopicPrefix: edgex/telemetry # /<service-name>/<metric-name> will be added to this Publish Topic prefix
    Metrics: # All service's metric names must be present in this list.
      # Device SDK provided Service Metrics
      EventsSent: false
      ReadingsSent: false
      # Common Security Service Metrics
      SecuritySecretsRequested: false
      SecuritySecretsStored: false
      SecurityConsulTokensRequested: false
      SecurityConsulTokenDuration: false
    Tags: {} # Contains the service level tags to be attached to all the service's metrics
     # Gateway="my-iot-gateway" # Tag must be added here or via Consul Env Override can only chnage existing value, not added new ones.
```

```json
{
  "Writable": {
    "LogLevel": "INFO",
    "InsecureSecrets": {
      "DB": {
        "path": "redisdb",
        "Secrets": {
          "username": "",
          "password": ""
        }
      },
      "MQTT": {
        "path": "credentials",
        "Secrets": {
          "username": "",
          "password": ""
        }
      }
    },
    "Reading": {
      "ReadingUnits": true
    },
    "Telemetry": {
      "Interval": "30s",
      "PublishTopicPrefix": "edgex/telemetry",
      "Metrics": {
        "EventsSent": false,
        "ReadingsSent": false,
        "SecuritySecretsRequested": false,
        "SecuritySecretsStored": false,
        "SecurityConsulTokensRequested": false,
        "SecurityConsulTokenDuration": false
      },
      "Tags": {}
    }
  }
}
```
