### DISCUSSION TITLE
device service usb camera access /dev/video* through docker-compose

### DISCUSSION THREAD

**Discussion by dipshirajput** [edgexfoundry/community#90] [Q&A]
Hi All,
I have developed a device service which is specifically for usb camera in order to capture images.
while creating its container, i have defined the following in docker-compose.yml file,

```
devices:
- /dev/video0:/dev/video0
```
also tried with the following,
```
volume:
- /dev/video0:/dev/video0
```
but still the container is unable to open this port. 

please let me know for suggestions. Thanks in advance.

**Comment by bnevis-i** [comment]
My offhand thought is that /dev/video0 is going to get you access to the screen buffer of your video display, not your USB device.

Look at https://github.com/edgexfoundry/edgex-compose/blob/main/compose-builder/add-device-usb-camera.yml.

```yaml
    device_cgroup_rules:
      - 'c 81:* rw' # c:character device 81:device major number(81=webcam) *:device minor number rw:read/write
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
```
